# Generated by Django 5.1.3 on 2025-03-14 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "Name",
                    models.CharField(
                        default=None, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("Payment", models.CharField(default=None, max_length=20)),
                ("Start_Time", models.DateTimeField(default=None, max_length=20)),
                ("End_Time", models.DateTimeField(default=None, max_length=20)),
                ("Order", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(default=None, max_length=150)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "Order_number",
                    models.CharField(
                        default=None, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("Start_Time", models.DateTimeField(default=None, max_length=20)),
                ("End_Time", models.DateTimeField(default=None, max_length=20)),
                ("NickName", models.CharField(default=None, max_length=20)),
                ("Email", models.CharField(default=None, max_length=20)),
                ("Payment", models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.CharField(default=None, max_length=20)),
                ("Password", models.CharField(default=None, max_length=25)),
                ("Money", models.IntegerField(default=0)),
                ("NickName", models.CharField(default=None, max_length=20)),
                ("Phone", models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
