# Generated by Django 5.1.3 on 2025-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Phone",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
