# Generated by Django 5.1.3 on 2025-03-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Order_Area",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
