# Generated by Django 5.1.3 on 2025-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_order_order_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="End_Time",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="area",
            name="Start_Time",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
