# Generated by Django 5.1.3 on 2025-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_area_end_time_alter_area_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="End_Time",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="Start_Time",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
