# Generated by Django 5.1.3 on 2025-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_order_end_time_alter_order_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="Order_number",
            field=models.CharField(
                default=None, max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
