# Generated by Django 5.1.3 on 2025-03-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="NickName",
        ),
    ]
